Config project
britodani/TestSuiteDigitalBank pull request #1
Opened 2022-05-27 13:58 UTC by britodani

Se realiza pull request con cambios de en el área de trabajo, con archivo de test y packeg

2022-05-27 16:05 UTC, rquintana-abstracta commented on test/specs/pruebahumo.js
> +      await browser.url('http://localhost:8080/bank');
Al haber configurado el `baseUrl:` como `http://localhost:8080/bank` en el archivo de configuracion (`wdio.conf.js`), no es necesario indicar la url completa durante la creacion del test: Unicamente la ruta especifica dentro del servidor:

En este caso, seria el root/home (simplemente `/`). Ya que wdio hace un "pre-pend" de esa parte para incluirlo en cada request, y te evita tener que repetir la url base todo el tiempo. 

ej.

```javascript
await browser.url('/');
```

2022-05-27 16:07 UTC, rquintana-abstracta commented on test/specs/pruebahumo.js
> +      await browser.pause(10000)
Esta linea solamente tiene sentido para motivos de debugging (cuando se necesita que se detenga la ejecucion en una seccion para verificar manualmente que es lo que se esta viendo) o para demostracion, pero cuando el codigo se publica, una de los objetivos que se busca es que pueda ejecutar rápido la suite, y esta pausa lo imposibilita.

Considera eliminar esa linea.

2022-05-27 16:09 UTC, rquintana-abstracta commented on test/specs/pruebahumo.js
> +      btn.click();
Esta es una operacion asincrona (wdio envia una request al navegador para realizar el click, lo que implica un uso de un recurso externo al entorno de ejecucion, por lo que node.js seguira ejecutando codigo sin esperar que se termine de ejecutar el click.), por lo tanto, necesita un await para indicarle explicitamente que espere a que se resuelva la operacion.

Cambialo a `await btn.click()`

2022-05-27 16:10 UTC, rquintana-abstracta commented on test/specs/pruebahumo.js
> +        await browser.pause(5000)
Mismo comentario respecto a eliminar las pausas al publicar el codigo

2022-05-27 16:13 UTC, rquintana-abstracta commented on test/specs/pruebahumo.js
> +        expect(await inf.getText()).toEqual('Account Number: 486130005')
Cuando se valida texto, a menos que el requerimiento sea realmente explicito al respecto, es mas seguro utilizar el matcher `.toHaveTextContaining()` en lugar de `.toEqual()` para evitar falsos positivos en caso de que hayan detalles que hagan que no sea estrictamente igual, pero de todas formas sea el resultado esperado desde el punto de vista de un usuario humano (como por ejemplo, que haya un espacio de mas, o que haya mas texto alrededor de ese principal), que son casos en que `toEqual()` fallaria pero `toHaveTextContaining()` pasaria, que es lo esperado.

2022-05-27 16:13 UTC, rquintana-abstracta requested changes
Realizar cambios sugeridos

2022-05-27 16:24 UTC, britodani commented on test/specs/pruebahumo.js
> +      await browser.url('http://localhost:8080/bank');
Si olvide comentar eso, que cuando lo dejaba de esta forma

await browser.url('/');

y al ejecutar **npm test run** no funcionaba, aun no se porque motivo, a su ves tuve que cambiar el comando para ejecutar **npm run wdio** y así fue que funciono. 

No toma el specs './test/specs/**/*.js' creo que por eso no funcionó lo de la url

2022-05-27 16:26 UTC, britodani commented on test/specs/pruebahumo.js
> +      await browser.pause(10000)
Lo coloque porque al llegar al home no mostraba las graficas, quizás como hace un proceso después de eso lo muestre, lo quitare (Y)

2022-05-30 14:18 UTC, britodani commented on test/specs/pruebahumo.js
> +      await browser.url('http://localhost:8080/bank');
Se realizo la modificación lo antes mencionado agregándole / al final de la url del (wdio.conf.js), también se modifico en el package.js en el "scripts" el **wdio** por **test** para usar el comando **npm test run**

2022-05-30 14:21 UTC, britodani commented on test/specs/pruebahumo.js
> +      await browser.pause(10000)
La línea await browser.pause(10000) se elimino por lo comentado anteriormente, se le dio uso debido a que el ejecutarse el test no se apreciaba lo que se estaba ejecutando para mejora de este se hizo cambio de navegador en wdio.config.js

2022-05-30 14:59 UTC, rquintana-abstracta approved these changes

2022-05-30 17:59 UTC, merged