Casos de Prueba genericos para implementar 1
britodani/TestSuiteDigitalBank pull request #4
Opened 2022-06-01 20:59 UTC by britodani

2022-06-01 21:17 UTC, rquintana-abstracta commented on CasosdePruebaDigitalBank1.md
> +**Validar login Bank**
Este es el unico test case que valida el login, el resto valida cosas asociadas a otras paginas, que estan fuera del scope de la tarea (pero van a ser utiles mas adelante cuando se cubran esas paginas)

Considera profundizar sobre el login y todos los casos asociados (ingreso de datos correctos, usuario incorrecto, contrase;a incorrecta, submit con enter, submit con click en enter, submit con "remember me", sumbit con campos vacios, etc)

2022-06-01 21:20 UTC, rquintana-abstracta commented on CasosdePruebaDigitalBank1.md
> +##Nombre
Dado que la estructura de la doc hace que cada test case comparta campos. (Todos tienen descripcion, precondiciones, etc), una vista en tabla podria mostrar la informacion de manera mas compacta, ayudando a la lectura y comprension.

Aca tenes documentacion para mostrarte la sintaxis para incluir tablas en markdown: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

2022-06-01 21:21 UTC, rquintana-abstracta requested changes
Implementa los cambios propuestos

2022-06-01 21:21 UTC, britodani commented on CasosdePruebaDigitalBank1.md
> +**Validar login Bank**
Ok. Perfecto, creare otro documento que contentan solo lo del login

2022-06-01 21:24 UTC, rquintana-abstracta commented on CasosdePruebaDigitalBank1.md
> +**Validar login Bank**
Preferentemente en este mismo (Borrando el resto), ya que de lo contrario, habria documentacion sobre casos que no van a ser implementados en el scope de este pull request

2022-06-02 19:54 UTC, rquintana-abstracta commented on CasosdePruebaDigitalBank1.md
> +|**Validar login Bank correcto**| Validar que se pueda loguiar con los usuarios y contraseña correctos.|<ul><li>Ambiente de trabajo instalado</li> <li>url del ambiente</li><li>usuario y contraseña</l
En todos los lugares donde aparezca "loguiar", cambiarlo por "loguear" (error ortografico).

2022-06-02 19:54 UTC, rquintana-abstracta requested changes
Implementa nuevos cambios

2022-06-02 20:07 UTC, rquintana-abstracta requested changes
Documentacion aprobada. Puede comenzar a automatizar test cases definidos

2022-06-02 20:13 UTC, britodani commented on CasosdePruebaDigitalBank1.md
> +|**Validar login Bank correcto**| Validar que se pueda loguiar con los usuarios y contraseña correctos.|<ul><li>Ambiente de trabajo instalado</li> <li>url del ambiente</li><li>usuario y contraseña</l
Subidos los cambios solicitados

2022-06-08 13:20 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +class Login extends BasePage{
Esta clase esta modelando una pagina, y "login" tambien hace referencia a la accion de loguearse. `LoginPage` seria un nombre mas descriptivo para lo que esta representando esta clase

2022-06-08 13:22 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get principal(){return $('.align-content')}
Que esta representando este elemento? Su nombre no es suficientemente descriptivo. Preferi un nombre que represente mejor al elemento y permita al lector orientarse mejor sin necesidad de inspeccionar la pagina en busca del elemento (mejorando la productividad del equipo al ahorrarle una busqueda).

Relacionado a esto, el selector se basa en una clase muy asociada a un estilo de layout que esta siendo aplicado (en este caso, un estilo de alineacion). Proba si podes encontrar un selector mas directamente asociado al elemento, asi lo haces mas robusto y lo proteges sobre posibles cambios "menores" (como por ejemplo, el estilo de alineacion) que lo podrian romper

2022-06-08 13:30 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get tittle(){return $('.login-logo')}
Este nombre tiene un typo: seria `title` (una sola "t" en el medio)

2022-06-08 13:35 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get usernamein(){ return $('#username') }
En general es preferible usar el nombre completo, y evitar abreviaciones, ya que asi se evitan ambiguedades y dificultades de interpretacion (otra vez, con el objetivo de hacer eficiente y facil el proceso de leer y entender el codigo: Actividades que se realizan mucho mas frecuentemente que la escritura de nuevo codigo, por lo tanto impactando en la productividad general del equipo). En este caso `usernameInput` es un nombre mas descriptivo (Otro detalle es que JavaScript usa camelCase como convencion para nombrar entidades, por eso la "I" de "input" esta capitalizada en el ejemplo que te di)

Ref: https://en.wikipedia.org/wiki/Camel_case

2022-06-08 13:36 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get passwordin(){return $('#password')}
Mismo comentario respecto a la abreviacion y convencion de uso de camelCase

2022-06-08 13:41 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get rememberme(){return $('#remember-me')}
Quizas agregarle al nombre la nocion de que tipo de elemento es este rememberme. En este caso es un checkbox. Esto completa el entendimiento de que es lo que esta representando esto para el lector: `rememberMeCheckBox` (teniendo en cuenta la convencion camelCase que usa JavaScript)

2022-06-08 13:45 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get signin(){return $('#submit')}
Misma idea que con el caso anterior: Quizas agregarle la nocion de que elemento es (en este caso, un button): `signInButton`

2022-06-08 13:54 UTC, britodani commented on test/pageobjects/Login.page.js
> +    get principal(){return $('.align-content')}
Ese esta representando el **Digital Bank**  igual con el comentario, me hiciste pensar que no tiene uso por los momentos, pero el siguiente atributo title haría lo que me comentas de buscar un mejor selector.

2022-06-08 13:57 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    get flash() {return $('.badge')}
No estoy seguro del nombre estandar de este tipo de elementos, pero quizas le podrias poner "login state feedback" (ya que su objetivo es darte feedback de si algo fallo en el login). Creo que asi quedaria mas claro inmediatamente al leerlo (y en su uso en los tests), ya que una assertion ahi se leeria: 

```javascript
await expect(LoginPage.loginStateFeedback).toHaveTextContaining("Error")
```

2022-06-08 14:04 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    async loguearclick(username,password){
Este nombre, en mi opinion, tiene algo de sobre-abreviacion. Podrias mejorarlo con un: `loguearseConClickEnBotonSubmit()` (puede parecer largo, pero los beneficios de la claridad que aporta, en mi opinion, son mucho mayores a los posibles "costos" de la longitud). Hay un principio en desarrollo de tests llamado DAMP (descriptive and meaningful phrases) que se suele usar al implementarlos, que es basicamente preferir implementaciones faciles de leer e interpretar, aunque a veces implique mas duplicacion (violar otro principio muy fuerte en software que es el DRY) (que no es el caso aca)

Ref: https://stackoverflow.com/questions/6453235/what-does-damp-not-dry-mean-when-talking-about-unit-tests

2022-06-08 14:42 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +   /*
Elimina codigo comentado. Es una instancia de "codigo muerto" (dead code). Con el uso de herramientas de versionado como git ya no tiene mas utilidad dejar codigo comentado (ya que podes volver atras en todo momento para ver el estado del proyecto en cualquier punto de la historia)

Ref: https://en.wikipedia.org/wiki/Dead_code

2022-06-08 14:47 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +        await this.vaciarCampoYEnviarTexto(await this.usernamein,username)
Este metodo repite varios pasos del de loguearse con click en el boton. Quizas se puede descomponer las operaciones un poco mas para evitar la duplicacion: Se me ocurre:

- Crear un metodo para la parte que "completar credenciales", que ambos metodos comparten
- Un metodo para hacer click en el boton de sign in
- Un metodo para hacer click en el checkbox de rememberme

Luego en la definicion del test se usan los metodos necesarios para cada comportameinto (ej, en el caso de loguearse con click, se usaran "completar credenciales", y "click en boton de sign in", mientras que para el de loguearse con "remember me", entre "completar credenciales" y "click en boton sign in" se llamaria a "click en checkbox de remember me")

2022-06-08 14:49 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    async loguearclickreme(username,password){
Mismo comentario respecto al metodo de loguearse con click: Preferir un nombre mas descriptivo y menos abreviado: Algo asi como `loguearseConRememberMe`

2022-06-08 14:50 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    async crearcta(){
El nombre de este metodo comunica una accion distinta a lo que la implementacion hace. Comunica que al ejecutarlo se va a crear una cuenta, mientras que la implementacion indica que navega hacia la pagina de registro.

Un nombre que describe mejor lo que realmente hace es: `irAPaginaDeSignUp`

2022-06-08 14:56 UTC, rquintana-abstracta commented on test/pageobjects/base.page.js
> +       await elemento.keys(texto);
Usando `setValue()`, que es un metodo de los web elements logra los mismos pasos descritos aqui, por lo que te ahorra dos lineas y te encapsula los detalles de como lo implementa (delegando a wdio su mantenimiento).

El metodo se reduce a:

```javascript
async vaciarCampoYEnviarTexto(elemento, texto){
  await elemento.waitForClickable({ timeout: PAGE_TIMEOUT });
  await elemento.setValue(text);
}
```

2022-06-08 15:06 UTC, rquintana-abstracta commented on test/pageobjects/form.page.js
> +class Form extends BasePage{
Que esta representando esta clase? Seria como solamente la parte del formulario de login? Si es asi, me parece que no es necesario ir a tanto detalle en este caso, ya que la pagina de login en general no tiene tantos elementos y acciones como para que no se pueda representar toda la pagina en una sola clase

2022-06-08 15:06 UTC, rquintana-abstracta commented on test/pageobjects/home.page.js
> +    get tittle(){return $('#page-title')}
Mismo comentario respecto al typo: Seria `title`

2022-06-08 15:08 UTC, rquintana-abstracta commented on test/pageobjects/home.page.js
> +    * Click en el resultado de la búsqueda
Este comentario no esta describiendo el metodo sobre el que se encuentra (quizas un copy paste del curso con open cart?)

2022-06-08 15:09 UTC, rquintana-abstracta commented on test/pageobjects/home.page.js
> +   async salirHome() {
Esto seria mas un "cerrar sesion" o "desloguearse" de acuerdo a como lo implementaste

2022-06-08 15:10 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +import login from '../pageobjects/Login.page';
La convencion en wdio es que los page objects se nombren igual que su clase (en este caso `Login` con mayuscula, aunque con la sugerencia que hice en esa seccion seria `LoginPage`)

2022-06-08 15:10 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +import homePage from '../pageobjects/home.page'
Mismo comentario respecto a convencion de nomenclatura de wdio

2022-06-08 15:14 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +describe('prubahumo', () => {
El `describe()` tipicamente se utiliza para describir el scope de la suite entera. En este caso, la suite es de tests del login. Una buena descripcion puede ser: `'Login Suite'`

2022-06-08 15:18 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +    it('login bank', async () => {
Una convencion que suele utilizarse para la descripcion de test cases es la de estructurarla de acuerdo a "DEBERIA....CUANDO" (o should/when). Hacerlo asi te lleva a enfocar el test en el resultado esperado (lo que **deberia** suceder), **cuando** ejecuto determinado _conjunto de acciones_ con determinado _conjunto de datos_, por lo que la accion y su resultado quedan determinados en el titulo. Luego de eso, definir el test resulta mas facil, ya que el objetivo quedo claro desde el inicio.

En este caso, una buena descripcion usando esa estructura podria ser: `Deberia acceder a la pagina principal cuando se loguea con credenciales validas`

2022-06-08 15:24 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +      await expect(login.flash).toHaveText('Success')
Con esta assertion lo que estas validando es que se haya **deslogueado** adecuadamente (ya que el test loguea y luego desloguea, lo que hace que se muestre el banner de "Success". Lo que tuvo exito ahi fue el deslogueo).

Como el test esta probando que se haya logueado exitosamente, preferi un assertion que indique eso adecuadamente. (Por ejemplo, que valide la existencia de cierto elemento dentro de home page luego de loguearse, que es lo que un usuario espera ver para validar que se pudo loguear exitosamente).

Remove la parte que desloguea de este test, ya que pertenece al scope de otra suite (la que pruebe el log out)

2022-06-08 15:25 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +    it('login bank user Invalido', async () => {
Mismo comentario respecto al patron de descripcion de tests (preferir algo basado en DEBERIA...CUANDO)

2022-06-08 15:25 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +    it('login bank con enter', async () => {
Remueve codigo comentado (dead code)

2022-06-08 15:26 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +      await expect(login.flash).toHaveText('Success')
Mismo comentario respecto al assertion validando un deslogueo en lugar de un logueo. Aplicar mismos cambios que en el primer caso

2022-06-08 15:27 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +    it('login bank pass Invalido', async () => {
Mismo comentario general para todas las descripciones de test cases

2022-06-08 15:28 UTC, rquintana-abstracta commented on test/pageobjects/form.page.js
> +class Form extends BasePage{
Al leer el test vi que esto representa el formulario de registro de un nuevo usuario. En ese caso me parece que esta correcto que tenga su propio page object. Mejora el nombre para que quede explicito que representa la pagina de registro de usuario

2022-06-08 15:29 UTC, rquintana-abstracta commented on test/pageobjects/form.page.js
> +get titform(){return $('=Title')}
Evita abreviaciones: `formTitle` en este caso es mas descriptiva

2022-06-08 15:30 UTC, rquintana-abstracta commented on test/pageobjects/home.page.js
> +   /**
Elimina codigo comentado

2022-06-08 15:31 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +    });
Comentario general respecto al nombre del archivo. Deberia indicar aproximadamente la suite que esta representando: En este caso es la suite de tests de login, no una prueba de humo, por lo tanto renombralo a algo como `login.test.js` que indica mas fielmente que tipo de tests se esperan.

2022-06-08 15:32 UTC, rquintana-abstracta requested changes
Implementa cambios sugeridos

2022-06-08 19:41 UTC, britodani commented on test/specs/pruebahumo.test.js
> +      await expect(login.flash).toHaveText('Success')
Acá use el desloguear mas que nada para que avanzara al siguiente test porque al no hacerlo me sale este error 

![image](https://user-images.githubusercontent.com/51838775/172703183-b9e83861-f601-4255-9d7e-8c0a14b4fa5f.png)

2022-06-08 20:02 UTC, rquintana-abstracta commented on test/specs/pruebahumo.test.js
> +      await expect(login.flash).toHaveText('Success')
Buen punto. Un workarround para solucionarlo es navegar explicitamente a la pagina del login en lugar de a la base url (ya que la aplicacion no implementa redireccion a home si detecta una sesion abierta, por ejemplo).

Seria: `LoginPage.abrir('login')` en lugar de `LoginPage.abrir('')` en cada test

2022-06-08 20:10 UTC, britodani commented on test/specs/pruebahumo.test.js
> +      await expect(login.flash).toHaveText('Success')
Ok. Hago esos cambios y te comento

2022-06-09 13:36 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    async ClickEnBotonSubmit(){
La convencion camelCase implica que los nombres empiezan con minuscula. Cambia a minuscula la "c" inicial

2022-06-09 13:36 UTC, rquintana-abstracta commented on test/pageobjects/Login.page.js
> +    async ClickEnCheckboxRememberMe(){
Mismo comentario respecto a camelCase. Cambia a minuscula la "c" inicial

2022-06-09 13:37 UTC, rquintana-abstracta requested changes
Implementa nuevo cambios y acciona sobre algunos comentarios anteriores que quedaron sin resolver

2022-06-09 15:21 UTC, rquintana-abstracta commented on test/pageobjects/registroUser.page.js
> +class RegistroUser extends BasePage{
esta es la pagina de registro de usuarios. Por lo tanto: `RegistroUsetPage` es un mejor nombre, consistente tambien con como venis nombrando el resto de los page objects

2022-06-09 15:22 UTC, rquintana-abstracta requested changes
Impelmenta cambios pendientes de revisiones anteriores (Mover el atributo title a BasePage por tratarse de un atributo presente en todas las paginas) y lo nuevo

2022-06-09 17:34 UTC, rquintana-abstracta approved these changes

2022-06-09 17:42 UTC, merged